#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

STALWART_URL="${STALWART_URL:-http://127.0.0.1:8088}"
DOMAIN="${DOMAIN:-jarlhalla.com}"
MAILBOX="${MAILBOX:-jarle}"
RECOVERY_FILE="${RECOVERY_FILE:-/root/jarlhalla-mail-recovery.txt}"
MAILBOX_FILE="${MAILBOX_FILE:-/root/jarlhalla-mailbox-jarle.txt}"
DNS_FILE="${DNS_FILE:-/root/jarlhalla-mail-dns.txt}"

if ! command -v stalwart-cli >/dev/null 2>&1; then
  echo "stalwart-cli is required." >&2
  echo "Install from the official Stalwart CLI release before running this script." >&2
  exit 1
fi

if [ ! -r "$RECOVERY_FILE" ]; then
  echo "Cannot read $RECOVERY_FILE" >&2
  exit 1
fi

ADMIN_PASSWORD="$(awk -F': ' '/^Password: / {print $2; exit}' "$RECOVERY_FILE")"
if [ -z "$ADMIN_PASSWORD" ]; then
  echo "Could not parse recovery administrator password." >&2
  exit 1
fi

CLI=(stalwart-cli --url "$STALWART_URL" --user admin --password "$ADMIN_PASSWORD" --no-color)

DOMAIN_ID="$(${CLI[@]} query domain --fields id,name --json \
  | jq -r --arg domain "$DOMAIN" 'select(.name == $domain) | .id' \
  | head -n1)"

if [ -z "$DOMAIN_ID" ]; then
  CREATE_OUTPUT="$(${CLI[@]} create domain \
    --field "name=$DOMAIN" \
    --field 'aliases={}' \
    --field 'certificateManagement={"@type":"Manual"}' \
    --field 'dkimManagement={"@type":"Automatic"}' \
    --field 'dnsManagement={"@type":"Manual"}' \
    --field 'subAddressing={"@type":"Enabled"}')"
  echo "$CREATE_OUTPUT"

  DOMAIN_ID="$(${CLI[@]} query domain --fields id,name --json \
    | jq -r --arg domain "$DOMAIN" 'select(.name == $domain) | .id' \
    | head -n1)"
fi

if [ -z "$DOMAIN_ID" ]; then
  echo "Failed to resolve Stalwart domain id for $DOMAIN" >&2
  exit 1
fi

ACCOUNT_ID="$(${CLI[@]} query account --fields id,name,domainId --json \
  | jq -r --arg name "$MAILBOX" --arg domainId "$DOMAIN_ID" \
    'select(.name == $name and .domainId == $domainId) | .id' \
  | head -n1)"

if [ -z "$ACCOUNT_ID" ]; then
  MAIL_PASSWORD="$(openssl rand -base64 30 | tr -d '\n')"

  ${CLI[@]} create account/user \
    --field "name=$MAILBOX" \
    --field "domainId=$DOMAIN_ID" \
    --field "description=Jarle Taksdal" \
    --field "credentials={\"0\":{\"@type\":\"Password\",\"secret\":\"$MAIL_PASSWORD\"}}" \
    --field 'memberGroupIds={}' \
    --field 'roles={"@type":"User"}' \
    --field 'permissions={"@type":"Inherit"}' \
    --field 'quotas={}' \
    --field 'aliases={}' \
    --field 'encryptionAtRest={"@type":"Disabled"}'

  cat > "$MAILBOX_FILE" <<EOF
Jarlhalla mailbox
Generated: $(date -Is)
Email: ${MAILBOX}@${DOMAIN}
Username: ${MAILBOX}@${DOMAIN}
Password: ${MAIL_PASSWORD}
IMAP: mail.${DOMAIN}:993 TLS
SMTP submission: mail.${DOMAIN}:587 STARTTLS
SMTP implicit TLS: mail.${DOMAIN}:465 TLS
EOF
  chmod 600 "$MAILBOX_FILE"
else
  echo "Mailbox already exists; password was not changed. Account id: $ACCOUNT_ID"
fi

${CLI[@]} get domain "$DOMAIN_ID" --fields dnsZoneFile --json \
  | jq -r '.dnsZoneFile // empty' > "$DNS_FILE"
chmod 600 "$DNS_FILE"

echo "Domain id: $DOMAIN_ID"
echo "Mailbox: ${MAILBOX}@${DOMAIN}"
echo "Mailbox credentials (new accounts only): $MAILBOX_FILE"
echo "DNS records generated by Stalwart: $DNS_FILE"
